name: Create ospsuite.reportingengine Linux images
on: 
  release:
    types: [released]
  pull_request:

jobs:
  build:
    strategy:
        matrix:
            r_version: [3.6.3] #[3.6.3, 4.1.0]
            os_version: [centos7, bionic]
    runs-on: ubuntu-latest
    env:
        OSPSUITE_R_VERSION: 10.0.25
        REPORTINGENGINE_VERSION: 1.2.40
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          build-args: |
            r_version=${{ matrix.r_version }}
            os_version=${{ matrix.os_version }}
            ospsuite_r_version=${{ env.OSPSUITE_R_VERSION }}
            re_version=${{ env.REPORTINGENGINE_VERSION }}
          push: ${{ github.event_name == 'release' }}
          tags: |
            ghcr.io/open-systems-pharmacology/reporting.engine-r${{ matrix.r_version }}-${{ matrix.os_version }}:${{ env.REPORTINGENGINE_VERSION }}
            ghcr.io/open-systems-pharmacology/reporting.engine-r${{ matrix.r_version }}-${{ matrix.os_version }}:latest
